/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PostListItem } from '../models/post-list-item';

/**
 * 統一 API 回傳格式
 */
export interface ApiResponsePostListItemArray {
  data: Array<PostListItem>;
}
