/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicTag } from '../models/public-tag';

/**
 * 分頁 API 回傳格式
 */
export interface PaginatedResponsePublicTag {
  data: Array<PublicTag>;
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}
