/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriesType } from '../models/categories-type';

/**
 * 文章列表項目（分類頁 / 主題頁用，不含 content 和 tags）
 */
export interface PostListItem {

  /**
   * 文章分類
   */
  categories: CategoriesType;

  /**
   * 建立時間（UTC）
   */
  createdAt: string;

  /**
   * 文章唯一識別碼
   */
  id: string;

  /**
   * 文章標題
   */
  title: string;

  /**
   * 所屬主題 ID
   */
  topicId: string | null;
}
