/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriesType } from '../models/categories-type';
import { PublicTag } from '../models/public-tag';
import { PublicTopic } from '../models/public-topic';

/**
 * 前台公開文章物件（不含 updatedAt）
 */
export interface PublicPost {

  /**
   * 文章分類
   */
  categories: CategoriesType;

  /**
   * 文章內文（Markdown）
   */
  content: string;

  /**
   * 建立時間（UTC）
   */
  createdAt: string;

  /**
   * 文章唯一識別碼（UUID）
   */
  id: string;

  /**
   * 文章標籤列表
   */
  tags: Array<PublicTag>;

  /**
   * 文章標題
   */
  title: string;

  /**
   * 所屬主題
   */
  topic: PublicTopic | null;

  /**
   * 所屬主題 ID
   */
  topicId: string | null;
}
