/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 前台公開標籤物件（不含後台管理欄位）
 */
export interface PublicTag {

  /**
   * 標籤 slug（前端當作路由使用）
   */
  id: string;

  /**
   * 標籤名稱
   */
  name: string;
}
