/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 後台完整標籤物件
 */
export interface Tag {

  /**
   * 建立時間（UTC）
   */
  createdAt: string;

  /**
   * 標籤id（前端當作路由使用）
   */
  id: string;

  /**
   * 標籤名稱
   */
  name: string;

  /**
   * 最後更新時間（UTC），未更新過則為 null
   */
  updatedAt: string;
}
